# Generated by Django 5.2.17 on 2026-08-19 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Todo title')),
                ('description', models.TextField(blank=True, verbose_name='Todo description')),
                ('completed', models.BooleanField(default=False, verbose_name="Todo's completion")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Todo creation time')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Todo update time')),
                ('notify_at', models.DateTimeField(blank=True, null=True, verbose_name='Todo notification time')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Todo sent to user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Todo author')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
